# -*- coding: utf-8 -*-
"""week 4 Data Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wCu5_kWiu_IjhdopqRXgErNeT-lR1Rgj

# **Student Survey Data Analysis and Visualization**
### **Tools Used**
- Pandas
- NumPy
- Matplotlib
- Seaborn

###**Libraries Install**
"""

!pip install pandas numpy matplotlib seaborn

"""###**Import Librarie**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("All libraries imported successfully!")

"""###**Load the Dataset & Clean the Dataset**"""

import pandas as pd

# Load the CSV file
df = pd.read_csv(
    "/content/Activity 01 (Responses).csv",
    sep="\t"
)

"""###**Check the Dataset**"""

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

"""###**Display First 5 Rows**"""

df.head()

"""###**Dataset Shape**"""

df.shape

"""###**Column Names**"""

df.columns

"""###**Data Types**"""

df.dtypes

"""###**Missing Values Analysis**"""

df.isnull().sum()

"""###**Handle Missing Values**"""

mode_value = df["When do you prefer to study?"].mode()[0]

print("Most common study time:", mode_value)
df["When do you prefer to study?"] = df[
    "When do you prefer to study?"
].fillna(mode_value)
df.isnull().sum()

"""###**Age Analysis**"""

age_counts = df["What is your age?"].value_counts()

print(age_counts)

"""###**Age Bar Chart**"""

plt.figure(figsize=(8,5))

plt.bar(
    age_counts.index,
    age_counts.values
)

plt.title("Distribution of Age")
plt.xlabel("Age Groups")
plt.ylabel("Number of Students")

plt.show()

"""###**Age Pie Chart**"""

plt.figure(figsize=(7,7))

plt.pie(
    age_counts,
    labels=age_counts.index,
    autopct="%1.1f%%"
)

plt.title("Distribution of Age")

plt.show()

"""###**Daily Screen Time Analysis**"""

screen_time_counts = df[
    "How many hours do you spend on screens daily? (including phone, laptop, tablets )"
].value_counts()

plt.figure(figsize=(9,5))

plt.bar(
    screen_time_counts.index,
    screen_time_counts.values
)

plt.title("Daily Screen Time")
plt.xlabel("Hours")
plt.ylabel("Number of Students")

plt.xticks(rotation=45)

plt.show()

"""###**Coffee or Tea Preference**"""

coffee_tea_counts = df[
    "Do you prefer coffee or tea?"
].value_counts()

plt.figure(figsize=(7,7))

plt.pie(
    coffee_tea_counts,
    labels=coffee_tea_counts.index,
    autopct="%1.1f%%"
)

plt.title("Coffee or Tea Preference")

plt.show()

"""###**Preferred Study Time**"""

study_time_counts = df[
    "When do you prefer to study?"
].value_counts()

plt.figure(figsize=(8,5))

plt.bar(
    study_time_counts.index,
    study_time_counts.values
)

plt.title("Preferred Study Time")
plt.xlabel("Time of Day")
plt.ylabel("Number of Students")

plt.show()

"""###**Social Media Preferences**"""

social_media_counts = df[
    "Which social media app do you prefer?"
].value_counts()

plt.figure(figsize=(9,5))

plt.bar(
    social_media_counts.index,
    social_media_counts.values
)

plt.title("Social Media App Preferences")
plt.xlabel("Social Media App")
plt.ylabel("Number of Students")

plt.xticks(rotation=45)

plt.show()

"""###**Hobbies and Interests**"""

hobbies_counts = df[
    "What are your hobbies / interest?"
].value_counts()

plt.figure(figsize=(9,6))

plt.barh(
    hobbies_counts.index,
    hobbies_counts.values
)

plt.title("Hobbies and Interests")
plt.xlabel("Number of Students")
plt.ylabel("Hobbies")

plt.show()

"""###**Languages Spoken**"""

language_counts = df[
    "How many languages do you speak fluently?"
].value_counts()

plt.figure(figsize=(8,5))

plt.bar(
    language_counts.index,
    language_counts.values
)

plt.title("Distribution of Number of Languages Spoken")
plt.xlabel("Number of Languages")
plt.ylabel("Number of Students")

plt.show()

"""###**Exercise Frequency**"""

exercise_counts = df[
    "How often do you exercise in a week?"
].value_counts()

plt.figure(figsize=(9,5))

plt.bar(
    exercise_counts.index,
    exercise_counts.values
)

plt.title("Exercise Frequency per Week")
plt.xlabel("Frequency")
plt.ylabel("Number of Students")

plt.xticks(rotation=45)

plt.show()

"""###**Pie chart for Exercise**"""

plt.figure(figsize=(7,7))

plt.pie(
    exercise_counts,
    labels=exercise_counts.index,
    autopct="%1.1f%%"
)

plt.title("Exercise Routine")

plt.show()

"""###**Commute Method**"""

commute_counts = df[
    "How do you primarily commute to work or school?"
].value_counts()

plt.figure(figsize=(9,5))

plt.bar(
    commute_counts.index,
    commute_counts.values
)

plt.title("Primary Commute Method Distribution")
plt.xlabel("Commute Method")
plt.ylabel("Number of Students")

plt.xticks(rotation=45)

plt.show()

"""###**Sleep Analysis**"""

sleep_counts = df[
    "How many hours of sleep do you get on an average night?"
].value_counts()

plt.figure(figsize=(9,5))

plt.bar(
    sleep_counts.index,
    sleep_counts.values
)

plt.title("Average Nightly Sleep Hours")
plt.xlabel("Hours")
plt.ylabel("Number of Students")

plt.xticks(rotation=45)

plt.show()

"""###P**ie chart for sleep**"""

plt.figure(figsize=(7,7))

plt.pie(
    sleep_counts,
    labels=sleep_counts.index,
    autopct="%1.1f%%"
)

plt.title("Average Nightly Sleep Hours")

plt.show()

"""###**Water Intake Analysis**"""

water_counts = df[
    "On average, how much water do you drink per day?"
].value_counts()

plt.figure(figsize=(9,5))

plt.bar(
    water_counts.index,
    water_counts.values
)

plt.title("Average Daily Water Intake")
plt.xlabel("Water Intake")
plt.ylabel("Number of Students")

plt.xticks(rotation=45)

plt.show()

"""###**Current Events Information Source**"""

source_counts = df[
    "What is your preferred method for staying informed about current events?"
].value_counts()

plt.figure(figsize=(9,5))

plt.bar(
    source_counts.index,
    source_counts.values
)

plt.title("Preferred Current Events Source")
plt.xlabel("Source")
plt.ylabel("Number of Students")

plt.xticks(rotation=45)

plt.show()

"""###**Bivariate Analysis**

###**Age vs Study Time**
"""

plt.figure(figsize=(9,5))

sns.countplot(
    x="What is your age?",
    hue="When do you prefer to study?",
    data=df
)

plt.title("Age vs Preferred Study Time")
plt.tight_layout()

plt.show()

"""###**Age vs Exercise**"""

plt.figure(figsize=(9,5))

sns.countplot(
    x="What is your age?",
    hue="How often do you exercise in a week?",
    data=df
)

plt.title("Age vs Exercise Frequency")
plt.tight_layout()

plt.show()

"""###**Screen Time vs Age**"""

plt.figure(figsize=(10,5))

sns.countplot(
    x="How many hours do you spend on screens daily? (including phone, laptop, tablets )",
    hue="What is your age?",
    data=df
)

plt.title("Screen Time vs Age")
plt.xticks(rotation=45)

plt.tight_layout()

plt.show()

"""###**Coffee/Tea vs Languages**"""

plt.figure(figsize=(9,5))

sns.countplot(
    x="How many languages do you speak fluently?",
    hue="Do you prefer coffee or tea?",
    data=df
)

plt.title("Coffee/Tea Preference vs Number of Languages Spoken")
plt.tight_layout()

plt.show()

"""###**Commute vs Exercise**"""

plt.figure(figsize=(10,5))

sns.countplot(
    x="How do you primarily commute to work or school?",
    hue="How often do you exercise in a week?",
    data=df
)

plt.title("Commute Method vs Exercise Frequency")

plt.xticks(rotation=45)
plt.tight_layout()

plt.show()

"""###**Sleep vs Screen Time**"""

plt.figure(figsize=(10,5))

sns.countplot(
    x="How many hours of sleep do you get on an average night?",
    hue="How many hours do you spend on screens daily? (including phone, laptop, tablets )",
    data=df
)

plt.title("Sleep Hours vs Daily Screen Time")

plt.xticks(rotation=45)
plt.tight_layout()

plt.show()

"""###**Save Cleaned Dataset**"""

df.to_csv(
    "/content/cleaned_student_survey.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

"""###**Internship Findings**

# 6. Key Findings

- The student survey dataset was successfully imported and analyzed.
- Missing values were identified and handled.
- Age distribution was analyzed using bar and pie charts.
- Screen time, study preferences, social media usage and hobbies were visualized.
- Exercise, sleep, water intake and commuting patterns were analyzed.
- Bivariate analysis was performed to study relationships between selected variables.
- The cleaned dataset was exported for further analysis.
"""