# -*- coding: utf-8 -*-
"""Week1_Data_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jyvqV79rjc_wNJnN_owkxRbhGokG9FZ4

# ***#Data Cleaning & Preprocessing***

# **Import Libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""#  **Load Dataset**"""

# Load Titanic dataset
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

"""# **Preview Dataset**"""

df.head()

"""# **Check Dataset Shape**"""

df.shape

"""# **Check Dataset Information**"""

df.info()

"""# **Check Column Names**"""

df.columns

"""# **Check Data Types**"""

df.dtypes

"""# **Check Missing Values**"""

df.isnull().sum()

"""# **Check Duplicate Rows**"""

df.duplicated().sum()

"""# **Remove Duplicate Rows**"""

df = df.drop_duplicates()

"""# **Fill Missing Values**"""

df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])
df['Cabin'] = df['Cabin'].fillna("Unknown")

"""# **Reset Index**"""

df.reset_index(drop=True, inplace=True)

"""# **Confirm Cleaning**"""

df.info()

"""# **Statistical Summary**"""

df.describe()

"""# **Mean**"""

df.mean(numeric_only=True)

"""# **Median**"""

df.median(numeric_only=True)

"""# **Mode**"""

df.mode().iloc[0]

"""# **Standard Deviation**"""

df.std(numeric_only=True)

"""## **Survival Count**"""

df['Survived'].value_counts()

"""# **Survival Percentage**"""

df['Survived'].value_counts(normalize=True) * 100

"""# ***#Data Analysis***

# **Unique Values in Survival**
"""

df['Survived'].unique()

"""# **Passenger Class Count**"""

df['Pclass'].value_counts()

"""# **Gender Count**"""

df['Sex'].value_counts()

"""# **Embarked Count**"""

df['Embarked'].value_counts()

"""# **Survival by Gender**"""

df.groupby('Sex')['Survived'].mean()

"""# **Survival by Passenger Class**"""

df.groupby('Pclass')['Survived'].mean()

"""# **Average Age by Survival**"""

df.groupby('Survived')['Age'].mean()

"""# **Average Fare by Passenger Class**"""

df.groupby('Pclass')['Fare'].mean()

"""# **Correlation Matrix**"""

corr_matrix = df.select_dtypes(include='number').corr()
corr_matrix

"""# **Correlation Heatmap**"""

plt.figure(figsize=(10,8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

"""# **#Data Visualization**

# **Survival Count Plot**
"""

sns.countplot(x='Survived', data=df)
plt.title("Survival Count")
plt.show()

"""# **Gender Count Plot**"""

sns.countplot(x='Sex', data=df)
plt.title("Gender Distribution")
plt.show()

"""# **Passenger Class Count Plot**"""

sns.countplot(x='Pclass', data=df)
plt.title("Passenger Class Distribution")
plt.show()

"""# **Survival by Gender**"""

sns.countplot(x='Sex', hue='Survived', data=df)
plt.title("Survival by Gender")
plt.show()

"""# **Age Distribution**"""

sns.histplot(df['Age'], bins=30, kde=True)
plt.title("Age Distribution")
plt.show()

"""# **Fare Distribution**"""

sns.histplot(df['Fare'], bins=30, kde=True)
plt.title("Fare Distribution")
plt.show()

"""# **Box Plot (Age vs Survival)**"""

sns.boxplot(x='Survived', y='Age', data=df)
plt.title("Age vs Survival")
plt.show()

"""# **Box Plot (Fare vs Passenger Class)**"""

sns.boxplot(x='Pclass', y='Fare', data=df)
plt.title("Fare by Passenger Class")
plt.show()

"""# **Scatter Plot**"""

sns.scatterplot(x='Age', y='Fare', hue='Survived', data=df)
plt.title("Age vs Fare")
plt.show()

"""# **Pair Plot**"""

sns.pairplot(df[['Age', 'Fare', 'Pclass', 'Survived']], hue='Survived')
plt.show()